config/routes.rb
TribeLights::Application.routes.draw do |map|


  match "/images/uploads/*path" => "gridfs#serve"

  resource :user, :only => [] 

  resource :profile

  resources :welcome, :only => [:index]
  resources :public_profiles, :only => [:index, :search] do
    collection do
      post :search
    end
    member do
      post :friend
    end
  end
  devise_for :users

  get "welcome/index"

  root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/name.rb
class Name
  include Mongoid::Document
  
  field :first, :type => String
  field :last, :type => String

  embedded_in :profile, :inverse_of => :name
  validates_presence_of :first, :last

  def full
    self.first + ' ' + self.last unless self.first.nil? || self.last.nil?
  end
  
end

app/models/profile.rb
require 'carrierwave/orm/mongoid'

class Profile
  include Mongoid::Document
  include Mongoid::Versioning
  field :birthday, :type => Date
  embeds_one :name
  accepts_nested_attributes_for :name
  referenced_in :user
  references_one :public_profile
  references_many :friends, :class_name => "PublicProfile", :stored_as => :array
  references_many :pending_friends, :class_name => "PublicProfile", :stored_as => :array
  validates_presence_of :user
  before_save :check_and_initialize_name, :create_public_profile

  mount_uploader :picture, AvatarUploader

  public 

  def pending_friend?(other_profile) 
    self.pending_friends.include?(other_profile)
  end

  protected
  def check_and_initialize_name
    self.create_name unless self.name
  end

  def create_public_profile
    if self.public_profile.nil? then
      self.public_profile = PublicProfile.new(:name => self.name.full,
       :birthday => self.birthday,:profile => self)
    else
      self.public_profile.attributes =  {:name => self.name.full,
       :birthday => self.birthday}
    end
    if self.picture?
      self.public_profile.picture_path = self.picture.url
      self.public_profile.thumb_path = self.picture.thumb.url
    end
    self.public_profile.save
  end
end

app/models/public_profile.rb
class PublicProfile
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :birthday, :type => Date
  field :picture_path, :type => String
  field :thumb_path, :type => String
  referenced_in :profile

  def pending_friend?(profile)
    profile.pending_friends.include?(self)
  end

  def friend?(profile)
    profile.friends.include?(self)
  end

end

app/models/user.rb
class User
  include Mongoid::Document

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  references_one :profile

  before_save :check_or_create_empty_profile

  private 
  def check_or_create_empty_profile
    self.profile = Profile.create if self.profile.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'

  before_filter :set_locale
  def set_locale
    # if params[:locale] is nil then I18n.default_locale will be used
    I18n.locale = params[:locale]
  end
end

app/controllers/gridfs_controller.rb
require 'mongo'

class GridfsController < ActionController::Metal
  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")
    begin
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  # GET /user/profile
  # GET /user/profile.xml
  def show
    @profile = current_user.profile

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end


  # GET /user/profile/edit
  def edit
    @profile = current_user.profile
  end


  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = current_user.profile

    respond_to do |format|
      logger.debug 'updating'
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(profile_url, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/public_profiles_controller.rb
class PublicProfilesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @public_profiles = PublicProfile.excludes(:profile_id => current_user.profile._id)
  end
  def search
    search_regular_expression = /#{params[:search]}/i
    @public_profiles = PublicProfile.find(:all, :conditions => {:name => search_regular_expression}).excludes(:profile_id => current_user.profile._id)
    respond_to do |format|
      format.js 
    end
  end
  def friend
    logger.debug("Param id #{params[:id]}")
    public_profile = PublicProfile.criteria.id(params[:id])
    if public_profile then
      current_user.profile.pending_friends << public_profile
    end
    @public_profiles = PublicProfile.find(:all, :conditions => {:name => search_regular_expression}).excludes(:profile_id => current_user.profile._id)
    respond_to do |format|
      format.js {render :action => "search"}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def after_sign_in_path_for(resource)
    root_url
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TribeLights</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery.js' %>
  <%= javascript_include_tag 'jquery-ui-1.8.2.custom.min.js' %>
  <%= javascript_include_tag 'jquery-ui-i18n.js' %>
  <%= javascript_include_tag 'rails.js' %>
  <%= javascript_include_tag 'application.js' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <input id="locale" type="hidden" name="locale" value="<%= I18n.locale %>" />

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1><%= t('profiles.edit.header') %></h1>
<div class="form edit">
  <%= form_for @profile, {:controller => 'profiles', :action => 'update', :url => profile_path, :html => {:multipart => true}} do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('profile.edit.errors', :errors => pluralize(@profile.errors.count, "error") ) %>:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.fields_for :name do |name_form| %>
      <div class="label"><%=  name_form.label :first, t('profiles.first_name').capitalize %></div>
      <div class="field"><%=  name_form.text_field :first  %></div>
      <div class="label"><%=  name_form.label :last, t('profiles.last_name').capitalize %></div>
      <div class="field"><%=  name_form.text_field :last  %></div>
    <% end %>
    <div class="label"><%= f.label :birthday, t('profiles.birthday').capitalize %></div>
    <div class="field"><%= f.text_field :birthday, :class => 'datepicker', :value => (@profile.birthday ? l(@profile.birthday) : '') %></div>
    <div class="avatar">
      <p>
      <%= f.label :picture, t('profiles.picture').capitalize %><br />
      <%= image_tag(@profile.picture_url) %>
      <%= f.file_field :picture %>
      <%= f.hidden_field :picture_cache %>
      </p>
    </div>
    <div class="field"><%= f.submit %></div>
  <% end %>
</div>
<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'profiles.show.header', :email => @profile.user.email %></h1>
<div>
  <%= image_tag(@profile.picture_url) %>
</div>
<p><%= t 'profiles.full_name' %>: <%= @profile.name.full %> </p>
<p><%= t 'profiles.birthday' %>: <%= l @profile.birthday, :format => :long unless @profile.birthday.nil? %> </p>

<ul id="profiles" class="list">
  <%= render @profile.friends %>
</ul>

<%= link_to 'Edit', edit_profile_path %> |

app/views/public_profiles/_public_profile.html.erb
<li class="public_profile item <%=cycle('odd', 'even') %>">
<div class="inline picture"><%= image_tag public_profile.thumb_path || '/images/thumb_default.png' %></div>
<div class="inline">
  <div class="header"><%= t('profiles.full_name').capitalize %>:<%= public_profile.name %></div>
  <div class="info"><%= t('profiles.birthday').capitalize %>:<%= l public_profile.birthday unless public_profile.birthday.nil?%></div>
</div>
<% if public_profile.pending_friend?(current_user.profile) then %>
  <%= t('profiles.friend_request_pending') %>
<% elsif public_profile.friend?(current_user.profile) then %>
  <%= t('profiles.already_friended') %>
<% else %>
  <div class="inline">
    <% form_tag({:controller => 'public_profiles', :action => 'friend', :id => public_profile.id }, { :remote => true})  do %>
      <%= submit_tag :friend, :value => t('profiles.list.buttons.friend') %>
    <% end %>
  </div>
<% end %>
</li>

app/views/public_profiles/index.html.erb
<h1><%= t('profiles.list.header').titlecase %></h1>
<div class="searchfield">
  <%= form_tag({:controller => 'public_profiles', :action => 'search'}, { :remote => true}) do %>
    <%= label_tag :search, t('profiles.search').capitalize %>
    <%= text_field_tag :search %>
    <%= submit_tag :go %>
  <% end %>
</div>
<ul id="profiles" class="list">
</ul>

app/views/public_profiles/search.js.erb
<% if @public_profiles.count > 0  then %>
  $('#profiles').html("<%=escape_javascript(render(@public_profiles))%>");
<% else %>
  $('#profiles').html("<%=escape_javascript(t('profiles.not_found')) %>");
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to TribeLights</h1>
<%- if user_signed_in? %>
  Welcome, <%= current_user.email %>
  <%= link_to "Sign Out", destroy_user_session_url %>
<% else %>
  <%=link_to "Sign In", user_session_url %>
<% end -%>